# --- Profili utente ---
# Qui definisci diversi tipi di "persone" da simulare.
# Ogni profilo ha caratteristiche cognitive e comportamentali diverse:
#
# - context_knowledge_factor: indica quanto conosce già l'azienda e dove trovare le informazioni.
#   valori più alti = ricerca più veloce, meno errori.
#
# - error_rate: probabilità di sbagliare (es. aprire file sbagliato).
#
# - cognitive_load_tolerance: quanta complessità riesce a gestire in un documento lungo o complesso.
#   valori bassi → rallenta se il documento è lungo o complesso.
#
# - short_term_memory_capacity: quante informazioni riesce a “tenere a mente” contemporaneamente.
#   se il documento è troppo grande rispetto a questa capacità, rallenta.
#
# - confidence: fiducia nelle proprie risposte.
#   valori bassi → tende a ripetere la ricerca per confermare la risposta anche se è già corretta.
#
# - stress_tolerance: quanto riesce a restare efficiente sotto stress o carichi di lavoro alti.
#   se il carico supera questo valore, aumenta la probabilità di errore e tempi più lunghi.

general_parameters:
  avg_clicks_to_find_doc: 5            # Click medi per trovare un documento
  avg_nav_time_per_click_sec: 3        # Secondi medi per ogni click
  avg_doc_open_time_sec: 5             # Secondi medi per aprire un documento
  avg_read_speed_words_per_sec: 3      # Parole al secondo lette mediamente
  avg_cognitive_processing_sec: 30     # Secondi di elaborazione mentale per documento
  avg_writing_speed_words_per_sec: 2   # Parole al secondo per scrivere la risposta
  doc_type_count: 5                    # Tipologie diverse di documenti disponibili
  min_documents_per_operation: 1       # Minimo documenti da consultare per rispondere
  max_documents_per_operation: 10      # Massimo documenti da consultare per rispondere

fatigue:
  nav_speed_factor: 1.2                # Fattore rallentamento navigazione fine giornata
  read_speed_factor: 1.5               # Fattore rallentamento lettura fine giornata
  processing_delay_factor: 1.3         # Fattore rallentamento ragionamento fine giornata
  error_rate_factor: 1.4               # Aumento errori fine giornata
  retries_factor: 1.3                  # Maggior numero di tentativi necessari fine giornata

document_sources:
  local_pc:
    probability: 0.4
    pages_range: [1, 30]           # documenti piccoli o medi
  sites_web:
    probability: 0.3
    pages_range: [5, 50]
  teams:
    probability: 0.2
    pages_range: [10, 70]
  email:
    probability: 0.1
    pages_range: [1, 20]           # Probabilità che il documento arrivi via mail

wait_times_sec:
  teams:
    min: 0                            # Tempo minimo attesa risposta Teams (sec)
    max: 0                          # Tempo massimo attesa risposta Teams (sec)
  email:
    min: 0                           # Tempo minimo attesa email (sec)
    max: 0                         # Tempo massimo attesa email (sec)

profiles:
  junior:
    hourly_rate: 15
    context_knowledge_factor: 0.3
    error_rate: 0.4
    cognitive_load_tolerance: 1.5
    short_term_memory_capacity: 4000
    confidence: 0.25
    stress_tolerance: 0.4

  mid:
    hourly_rate: 25
    context_knowledge_factor: 0.6
    error_rate: 0.3
    cognitive_load_tolerance: 3.5
    short_term_memory_capacity: 10000
    confidence: 0.6
    stress_tolerance: 0.65

  senior:
    hourly_rate: 45
    context_knowledge_factor: 1
    error_rate: 0.03
    cognitive_load_tolerance: 7.0
    short_term_memory_capacity: 20000
    confidence: 1
    stress_tolerance: 1

task:
  complexity_distribution:
    low: 60
    medium: 30
    high: 10  
    
complexity_ranges:
  low: [1, 3]
  medium: [4, 7]
  high: [8, 10]

profile_assignment:
  junior_max: 3
  mid_min: 4
  mid_max: 7
  senior_min: 8

organizations:
  profiles:
    junior: 50
    mid: 40
    senior: 10

